name: Deploy fastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push the Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/fastapiapi:latest
          docker build -t $IMAGE_NAME .
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_NAME
